/* ------------------------------------------------------------------------
 * eeprom.c
 *
 * FAKE non-volatile parameter storage. Backed by a plain local file
 * (pacer_nvram.bin) standing in for real EEPROM. NOT REAL. See
 * README.md at project root.
 *
 * Legacy smells seeded here on purpose:
 *   - a second, independent CRC16 implementation (telemetry.c already
 *     has its own checksum, computing something different) with the
 *     classic reflected polynomial table generated by hand every call
 *     instead of a precomputed const table
 *   - save/load functions that both duplicate the "serialize struct
 *     fields into globals" mapping instead of sharing one conversion
 *     routine
 *   - silent fallback to defaults on almost any failure, with no
 *     distinction between "file missing" and "file corrupt"
 * ------------------------------------------------------------------------
 */

#include "pacer.h"

/* Table-less CRC16/ARC-ish implementation, recomputed bit-by-bit every
 * call instead of using a lookup table - slow, but "that's how the
 * original bootloader team wrote it in 2009" per a since-departed
 * teammate, according to the (fictional) commit history. */
UINT16 crc16_calc(const BYTE *data, int len)
{
    UINT16 crc;
    int i;
    int bit;

    crc = 0xFFFF;

    for (i = 0; i < len; i++) {
        crc ^= (UINT16)data[i];

        for (bit = 0; bit < 8; bit++) {
            if (crc & 0x0001) {
                crc = (UINT16)((crc >> 1) ^ CRC16_POLY);
            } else {
                crc = (UINT16)(crc >> 1);
            }
        }
    }

    return crc;
}

void eeprom_defaults(NvramParams_t *p)
{
    if (p == NULL) {
        return;
    }

    memset(p, 0, sizeof(NvramParams_t));

    p->magic = NVRAM_MAGIC;
    p->mode = (BYTE)MODE_DDD;
    p->lrl_ms = DEFAULT_LRL_MS;
    p->url_ms = DEFAULT_URL_MS;
    p->avi_ms = DEFAULT_AVI_MS;
    p->pvarp_ms = DEFAULT_PVARP_MS;
    p->vrp_ms = DEFAULT_VRP_MS;
    p->arp_ms = DEFAULT_ARP_MS;
    p->pace_ampl_mv = DEFAULT_PACE_AMPL_MV;
    p->pace_width_ms = DEFAULT_PACE_WIDTH_MS;
    p->a_sense_thresh_mv = A_SENSE_THRESH_MV;
    p->v_sense_thresh_mv = V_SENSE_THRESH_MV;
    p->rate_resp_enabled = 0;
}

int eeprom_validate(const NvramParams_t *p, UINT16 stored_crc)
{
    UINT16 calc;

    if (p == NULL) {
        return 0;
    }

    if (p->magic != NVRAM_MAGIC) {
        return 0;
    }

    calc = crc16_calc((const BYTE *)p, (int)sizeof(NvramParams_t));
    if (calc != stored_crc) {
        return 0;
    }

    /* a handful of ad-hoc sanity checks bolted on later, none of them
     * using named bounds constants */
    if (p->lrl_ms < 300 || p->lrl_ms > 2000) {
        return 0;
    }
    if (p->url_ms < 250 || p->url_ms > 1500) {
        return 0;
    }
    if (p->mode >= MODE_COUNT) {
        return 0;
    }

    return 1;
}

/* Loads params from NVRAM_FILE if present and valid; otherwise silently
 * falls back to defaults AND writes them back out, conflating "load"
 * with "load-or-initialize". Returns 1 if a valid saved file was found,
 * 0 if defaults were used for any reason (missing file, short read,
 * bad CRC, bad magic - all treated identically, no differentiation in
 * the return value, only in a printf if verbose). */
int eeprom_load(void)
{
    FILE *fp;
    NvramParams_t params;
    UINT16 stored_crc;
    size_t n;

    fp = fopen(NVRAM_FILE, "rb");
    if (fp == NULL) {
        if (g_verbose) {
            printf("[eeprom] no NVRAM file found, using defaults\n");
        }
        goto use_defaults;
    }

    n = fread(&params, 1, sizeof(NvramParams_t), fp);
    if (n != sizeof(NvramParams_t)) {
        fclose(fp);
        if (g_verbose) {
            printf("[eeprom] short read on NVRAM file, using defaults\n");
        }
        goto use_defaults;
    }

    n = fread(&stored_crc, 1, sizeof(UINT16), fp);
    fclose(fp);

    if (n != sizeof(UINT16)) {
        if (g_verbose) {
            printf("[eeprom] missing CRC in NVRAM file, using defaults\n");
        }
        goto use_defaults;
    }

    if (!eeprom_validate(&params, stored_crc)) {
        if (g_verbose) {
            printf("[eeprom] NVRAM validation failed, using defaults\n");
        }
        goto use_defaults;
    }

    /* manual field-by-field copy into globals - duplicated (with the
     * reverse direction) in eeprom_save() below instead of a shared
     * pack/unpack helper */
    g_mode = (PaceMode_t)params.mode;
    g_lrl_ms = params.lrl_ms;
    g_url_ms = params.url_ms;
    g_avi_ms = params.avi_ms;
    g_pvarp_ms = params.pvarp_ms;
    g_vrp_ms = params.vrp_ms;
    g_arp_ms = params.arp_ms;
    g_pace_ampl_mv = params.pace_ampl_mv;
    g_pace_width_ms = params.pace_width_ms;
    g_a_sense_thresh_mv = params.a_sense_thresh_mv;
    g_v_sense_thresh_mv = params.v_sense_thresh_mv;
    g_rate_resp_enabled = params.rate_resp_enabled;

    return 1;

use_defaults:
    {
        NvramParams_t d;
        eeprom_defaults(&d);

        g_mode = (PaceMode_t)d.mode;
        g_lrl_ms = d.lrl_ms;
        g_url_ms = d.url_ms;
        g_avi_ms = d.avi_ms;
        g_pvarp_ms = d.pvarp_ms;
        g_vrp_ms = d.vrp_ms;
        g_arp_ms = d.arp_ms;
        g_pace_ampl_mv = d.pace_ampl_mv;
        g_pace_width_ms = d.pace_width_ms;
        g_a_sense_thresh_mv = d.a_sense_thresh_mv;
        g_v_sense_thresh_mv = d.v_sense_thresh_mv;
        g_rate_resp_enabled = d.rate_resp_enabled;

        eeprom_save();
    }

    return 0;
}

int eeprom_save(void)
{
    FILE *fp;
    NvramParams_t params;
    UINT16 crc;
    size_t n;

    memset(&params, 0, sizeof(params));
    params.magic = NVRAM_MAGIC;
    params.mode = (BYTE)g_mode;
    params.lrl_ms = g_lrl_ms;
    params.url_ms = g_url_ms;
    params.avi_ms = g_avi_ms;
    params.pvarp_ms = g_pvarp_ms;
    params.vrp_ms = g_vrp_ms;
    params.arp_ms = g_arp_ms;
    params.pace_ampl_mv = g_pace_ampl_mv;
    params.pace_width_ms = g_pace_width_ms;
    params.a_sense_thresh_mv = g_a_sense_thresh_mv;
    params.v_sense_thresh_mv = g_v_sense_thresh_mv;
    params.rate_resp_enabled = g_rate_resp_enabled;

    crc = crc16_calc((const BYTE *)&params, (int)sizeof(NvramParams_t));

    fp = fopen(NVRAM_FILE, "wb");
    if (fp == NULL) {
        if (g_verbose) {
            printf("[eeprom] failed to open %s for writing\n", NVRAM_FILE);
        }
        return 0;
    }

    n = fwrite(&params, 1, sizeof(params), fp);
    if (n != sizeof(params)) {
        fclose(fp);
        return 0;
    }

    n = fwrite(&crc, 1, sizeof(crc), fp);
    fclose(fp);

    if (n != sizeof(crc)) {
        return 0;
    }

    return 1;
}
